name: Bug Report
description: Report an issue you encountered.
labels: 
- bug

body:
- type: markdown
  attributes:
    value: Before filing this bug, [please check if it hasn't already been reported](https://github.com/TheSuperHackers/GeneralsGamePatch/issues?q=is%3Aissue%20state%3Aopen%20label%3ABug). If it has, please add useful information to the existing issue instead.

- type: dropdown
  attributes:
    label: Area(s) with this issue?
    description: What things had an issue? Check all that apply.
    multiple: true
    options:
      - The bug also exists in the original C&C Generals (Not Zero Hour)
      - The bug also exists in the Zero Hour Expansion Pack
      - This bug is a graphical glitch or error
      - This is a development issue
  validations:
    required: false

- type: textarea
  attributes:
    label: Describe the issue
    description: Please describe the issue you are experiencing here.
  validations:
    required: true


- type: textarea
  attributes:
    label: Steps to reproduce
    description: Outline the steps you took to reproduce this bug.
    placeholder: |
      Tell us the steps required to trigger your bug. Example:
      1. Open the attached save file
      2. Click on the command center
      3. The game crashes
  validations:
    required: true

- type: textarea
  attributes:
    label: Attachments
    description: Please add any screenshots, save files and/or videos here that may help us fix the issue.
    placeholder: Drag and drop files here to add them
  validations:
    required: false
