name: Linux-64 Testing
on:
  push:
  pull_request:
    branches:
      - develop
      - main

jobs:
  job:
    name: Linux 64-bit Testing
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest

      # Setup vcpkg: ensures vcpkg is downloaded and built.
      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "testing"
          buildPreset: "testing"
          testPreset: "default"
          generator: "Ninja"